/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @s2-dev/streamstore SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx accessTokensListAccessTokens.ts
 */

import { S2 } from "@s2-dev/streamstore";

const s2 = new S2({
  accessToken: process.env["S2_ACCESS_TOKEN"] ?? "",
});

async function main() {
  const result = await s2.listAccessTokens({});

  console.log(result);
}

main().catch(console.error);
