/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteOnEmptyReconfiguration = {
  /**
   * Minimum age in seconds before an empty stream can be deleted.
   *
   * @remarks
   * Set to 0 to disable delete-on-empty (don't delete automatically).
   */
  minAgeSecs?: number | null | undefined;
};

/** @internal */
export const DeleteOnEmptyReconfiguration$inboundSchema: z.ZodType<
  DeleteOnEmptyReconfiguration,
  z.ZodTypeDef,
  unknown
> = z.object({
  min_age_secs: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    "min_age_secs": "minAgeSecs",
  });
});

/** @internal */
export type DeleteOnEmptyReconfiguration$Outbound = {
  min_age_secs?: number | null | undefined;
};

/** @internal */
export const DeleteOnEmptyReconfiguration$outboundSchema: z.ZodType<
  DeleteOnEmptyReconfiguration$Outbound,
  z.ZodTypeDef,
  DeleteOnEmptyReconfiguration
> = z.object({
  minAgeSecs: z.nullable(z.number().int()).optional(),
}).transform((v) => {
  return remap$(v, {
    minAgeSecs: "min_age_secs",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteOnEmptyReconfiguration$ {
  /** @deprecated use `DeleteOnEmptyReconfiguration$inboundSchema` instead. */
  export const inboundSchema = DeleteOnEmptyReconfiguration$inboundSchema;
  /** @deprecated use `DeleteOnEmptyReconfiguration$outboundSchema` instead. */
  export const outboundSchema = DeleteOnEmptyReconfiguration$outboundSchema;
  /** @deprecated use `DeleteOnEmptyReconfiguration$Outbound` instead. */
  export type Outbound = DeleteOnEmptyReconfiguration$Outbound;
}

export function deleteOnEmptyReconfigurationToJSON(
  deleteOnEmptyReconfiguration: DeleteOnEmptyReconfiguration,
): string {
  return JSON.stringify(
    DeleteOnEmptyReconfiguration$outboundSchema.parse(
      deleteOnEmptyReconfiguration,
    ),
  );
}

export function deleteOnEmptyReconfigurationFromJSON(
  jsonString: string,
): SafeParseResult<DeleteOnEmptyReconfiguration, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteOnEmptyReconfiguration$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteOnEmptyReconfiguration' from JSON`,
  );
}
