/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteOnEmptyConfig = {
  /**
   * Minimum age in seconds before an empty stream can be deleted.
   *
   * @remarks
   * Set to 0 (default) to disable delete-on-empty (don't delete automatically).
   */
  minAgeSecs?: number | undefined;
};

/** @internal */
export const DeleteOnEmptyConfig$inboundSchema: z.ZodType<
  DeleteOnEmptyConfig,
  z.ZodTypeDef,
  unknown
> = z.object({
  min_age_secs: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    "min_age_secs": "minAgeSecs",
  });
});

/** @internal */
export type DeleteOnEmptyConfig$Outbound = {
  min_age_secs?: number | undefined;
};

/** @internal */
export const DeleteOnEmptyConfig$outboundSchema: z.ZodType<
  DeleteOnEmptyConfig$Outbound,
  z.ZodTypeDef,
  DeleteOnEmptyConfig
> = z.object({
  minAgeSecs: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    minAgeSecs: "min_age_secs",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteOnEmptyConfig$ {
  /** @deprecated use `DeleteOnEmptyConfig$inboundSchema` instead. */
  export const inboundSchema = DeleteOnEmptyConfig$inboundSchema;
  /** @deprecated use `DeleteOnEmptyConfig$outboundSchema` instead. */
  export const outboundSchema = DeleteOnEmptyConfig$outboundSchema;
  /** @deprecated use `DeleteOnEmptyConfig$Outbound` instead. */
  export type Outbound = DeleteOnEmptyConfig$Outbound;
}

export function deleteOnEmptyConfigToJSON(
  deleteOnEmptyConfig: DeleteOnEmptyConfig,
): string {
  return JSON.stringify(
    DeleteOnEmptyConfig$outboundSchema.parse(deleteOnEmptyConfig),
  );
}

export function deleteOnEmptyConfigFromJSON(
  jsonString: string,
): SafeParseResult<DeleteOnEmptyConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteOnEmptyConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteOnEmptyConfig' from JSON`,
  );
}
