/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  SequencedRecordBatch,
  SequencedRecordBatch$inboundSchema,
  SequencedRecordBatch$Outbound,
  SequencedRecordBatch$outboundSchema,
} from "./sequencedrecordbatch.js";

/**
 * Tail of the stream, i.e. sequence number that will be assigned to the next record.
 *
 * @remarks
 * It will primarily be returned either because the requested starting point was larger,
 * or only in case of a limited read, equal to the tail.
 * It will also be returned if there are no records on the stream between the requested
 * starting point and the tail.
 */
export type NextSeqNum = {
  /**
   * Tail of the stream, i.e. sequence number that will be assigned to the next record.
   *
   * @remarks
   * It will primarily be returned either because the requested starting point was larger,
   * or only in case of a limited read, equal to the tail.
   * It will also be returned if there are no records on the stream between the requested
   * starting point and the tail.
   */
  nextSeqNum: number;
};

/**
 * Batch of records.
 *
 * @remarks
 * It can only be empty outside of a session context,
 * if the request cannot be satisfied without violating its limit.
 */
export type Batch = {
  /**
   * A batch of sequenced records.
   */
  batch: SequencedRecordBatch;
};

/**
 * Batch of records or the next sequence number on the stream.
 */
export type Output = Batch | NextSeqNum;

/** @internal */
export const NextSeqNum$inboundSchema: z.ZodType<
  NextSeqNum,
  z.ZodTypeDef,
  unknown
> = z.object({
  next_seq_num: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    "next_seq_num": "nextSeqNum",
  });
});

/** @internal */
export type NextSeqNum$Outbound = {
  next_seq_num: number;
};

/** @internal */
export const NextSeqNum$outboundSchema: z.ZodType<
  NextSeqNum$Outbound,
  z.ZodTypeDef,
  NextSeqNum
> = z.object({
  nextSeqNum: z.number().int(),
}).transform((v) => {
  return remap$(v, {
    nextSeqNum: "next_seq_num",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NextSeqNum$ {
  /** @deprecated use `NextSeqNum$inboundSchema` instead. */
  export const inboundSchema = NextSeqNum$inboundSchema;
  /** @deprecated use `NextSeqNum$outboundSchema` instead. */
  export const outboundSchema = NextSeqNum$outboundSchema;
  /** @deprecated use `NextSeqNum$Outbound` instead. */
  export type Outbound = NextSeqNum$Outbound;
}

export function nextSeqNumToJSON(nextSeqNum: NextSeqNum): string {
  return JSON.stringify(NextSeqNum$outboundSchema.parse(nextSeqNum));
}

export function nextSeqNumFromJSON(
  jsonString: string,
): SafeParseResult<NextSeqNum, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NextSeqNum$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NextSeqNum' from JSON`,
  );
}

/** @internal */
export const Batch$inboundSchema: z.ZodType<Batch, z.ZodTypeDef, unknown> = z
  .object({
    batch: SequencedRecordBatch$inboundSchema,
  });

/** @internal */
export type Batch$Outbound = {
  batch: SequencedRecordBatch$Outbound;
};

/** @internal */
export const Batch$outboundSchema: z.ZodType<
  Batch$Outbound,
  z.ZodTypeDef,
  Batch
> = z.object({
  batch: SequencedRecordBatch$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Batch$ {
  /** @deprecated use `Batch$inboundSchema` instead. */
  export const inboundSchema = Batch$inboundSchema;
  /** @deprecated use `Batch$outboundSchema` instead. */
  export const outboundSchema = Batch$outboundSchema;
  /** @deprecated use `Batch$Outbound` instead. */
  export type Outbound = Batch$Outbound;
}

export function batchToJSON(batch: Batch): string {
  return JSON.stringify(Batch$outboundSchema.parse(batch));
}

export function batchFromJSON(
  jsonString: string,
): SafeParseResult<Batch, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Batch$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Batch' from JSON`,
  );
}

/** @internal */
export const Output$inboundSchema: z.ZodType<Output, z.ZodTypeDef, unknown> = z
  .union([
    z.lazy(() => Batch$inboundSchema),
    z.lazy(() => NextSeqNum$inboundSchema),
  ]);

/** @internal */
export type Output$Outbound = Batch$Outbound | NextSeqNum$Outbound;

/** @internal */
export const Output$outboundSchema: z.ZodType<
  Output$Outbound,
  z.ZodTypeDef,
  Output
> = z.union([
  z.lazy(() => Batch$outboundSchema),
  z.lazy(() => NextSeqNum$outboundSchema),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Output$ {
  /** @deprecated use `Output$inboundSchema` instead. */
  export const inboundSchema = Output$inboundSchema;
  /** @deprecated use `Output$outboundSchema` instead. */
  export const outboundSchema = Output$outboundSchema;
  /** @deprecated use `Output$Outbound` instead. */
  export type Outbound = Output$Outbound;
}

export function outputToJSON(output: Output): string {
  return JSON.stringify(Output$outboundSchema.parse(output));
}

export function outputFromJSON(
  jsonString: string,
): SafeParseResult<Output, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Output$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Output' from JSON`,
  );
}
