/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const StreamMetricSet = {
  Storage: "storage",
} as const;
export type StreamMetricSet = ClosedEnum<typeof StreamMetricSet>;

/** @internal */
export const StreamMetricSet$inboundSchema: z.ZodNativeEnum<
  typeof StreamMetricSet
> = z.nativeEnum(StreamMetricSet);

/** @internal */
export const StreamMetricSet$outboundSchema: z.ZodNativeEnum<
  typeof StreamMetricSet
> = StreamMetricSet$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace StreamMetricSet$ {
  /** @deprecated use `StreamMetricSet$inboundSchema` instead. */
  export const inboundSchema = StreamMetricSet$inboundSchema;
  /** @deprecated use `StreamMetricSet$outboundSchema` instead. */
  export const outboundSchema = StreamMetricSet$outboundSchema;
}
