/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiChatSnapshotRouteImport } from './routes/api.chat.snapshot'
import { Route as ApiChatReplayRouteImport } from './routes/api.chat.replay'
import { Route as ApiChatHistoryRouteImport } from './routes/api.chat.history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatSnapshotRoute = ApiChatSnapshotRouteImport.update({
  id: '/snapshot',
  path: '/snapshot',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatReplayRoute = ApiChatReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiChatHistoryRoute = ApiChatHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ApiChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/chat/history': typeof ApiChatHistoryRoute
  '/api/chat/replay': typeof ApiChatReplayRoute
  '/api/chat/snapshot': typeof ApiChatSnapshotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/chat/history': typeof ApiChatHistoryRoute
  '/api/chat/replay': typeof ApiChatReplayRoute
  '/api/chat/snapshot': typeof ApiChatSnapshotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/chat/history': typeof ApiChatHistoryRoute
  '/api/chat/replay': typeof ApiChatReplayRoute
  '/api/chat/snapshot': typeof ApiChatSnapshotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/chat/history'
    | '/api/chat/replay'
    | '/api/chat/snapshot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/chat/history'
    | '/api/chat/replay'
    | '/api/chat/snapshot'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/chat/history'
    | '/api/chat/replay'
    | '/api/chat/snapshot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/snapshot': {
      id: '/api/chat/snapshot'
      path: '/snapshot'
      fullPath: '/api/chat/snapshot'
      preLoaderRoute: typeof ApiChatSnapshotRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/replay': {
      id: '/api/chat/replay'
      path: '/replay'
      fullPath: '/api/chat/replay'
      preLoaderRoute: typeof ApiChatReplayRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/chat/history': {
      id: '/api/chat/history'
      path: '/history'
      fullPath: '/api/chat/history'
      preLoaderRoute: typeof ApiChatHistoryRouteImport
      parentRoute: typeof ApiChatRoute
    }
  }
}

interface ApiChatRouteChildren {
  ApiChatHistoryRoute: typeof ApiChatHistoryRoute
  ApiChatReplayRoute: typeof ApiChatReplayRoute
  ApiChatSnapshotRoute: typeof ApiChatSnapshotRoute
}

const ApiChatRouteChildren: ApiChatRouteChildren = {
  ApiChatHistoryRoute: ApiChatHistoryRoute,
  ApiChatReplayRoute: ApiChatReplayRoute,
  ApiChatSnapshotRoute: ApiChatSnapshotRoute,
}

const ApiChatRouteWithChildren =
  ApiChatRoute._addFileChildren(ApiChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
